name: Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


env:
  DOTNET_VERSION: 8.0.x
  BUILD_TARGET: .\src\VirtualDesktop.sln


jobs:
  build:
    name: .NET Build
    runs-on: windows-latest
    # Don't build for release the publish workflow will do that to
    if: "!startsWith(github.event.head_commit.message, 'Release v')"
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Use .NET ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
      
    - name: Build
      run: dotnet build ${{ env.BUILD_TARGET }} -c Release

    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Test-Artifact
        path: "D:\\a\\VirtualDesktop\\VirtualDesktop"

  publish:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: write
    steps:
    - name: Create directories for Build Artifacts to download
      run: |
        mkdir Test-Build
        ls -la
    
    - name: Download Build Artifacts
      uses: actions/download-artifact@v3.0.2
      with:
        name: Test-Artifact
        path: Test-Build


    - name: Compress
      run: |
        cd Test-Build
        ls -la
        zip -r Test-Build.zip ./
        
    - name: Create Draft Release and Upload Build Artifacts
      uses: ncipollo/release-action@v1.10.0
      with:
        name: "test name"
        draft: true
        artifacts:
          Test-Build.zip
